### ISSUE TITLE
ran into an error trying to use application. i'm not sure what exactly happened. i can share extra info if this is not enough

### ISSUE THREAD

**Issue by 22144418** [ThatOneCalculator/PyJumpcutterV2#1]
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    INPUT_FILE = downloadFile(urlget)
  File "jumpcutter.py", line 13, in downloadFile
    name = YouTube(url).streams.first().download()
  File "C:\Python37\lib\site-packages\pytube\__main__.py", line 70, in __init__
    self.video_id = extract.video_id(url)
  File "C:\Python37\lib\site-packages\pytube\extract.py", line 63, in video_id
    return regex_search(r'(?:v=|\/)([0-9A-Za-z_-]{11}).*', url, group=1)
  File "C:\Python37\lib\site-packages\pytube\helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern ((?:v=|\/)([0-9A-Za-z_-]{11}).*) had zero matches

**Comment by Tremeschin** [comment]
> Traceback (most recent call last):
> File "jumpcutter.py", line 108, in
> INPUT_FILE = downloadFile(urlget)
> File "jumpcutter.py", line 13, in downloadFile
> name = YouTube(url).streams.first().download()
> File "C:\Python37\lib\site-packages\pytube__main__.py", line 70, in **init**
> self.video_id = extract.video_id(url)
> File "C:\Python37\lib\site-packages\pytube\extract.py", line 63, in video_id
> return regex_search(r'(?:v=|/)([0-9A-Za-z_-]{11})._', url, group=1) File "C:\Python37\lib\site-packages\pytube\helpers.py", line 65, in regex_search .format(pattern=pattern), pytube.exceptions.RegexMatchError: regex pattern ((?:v=|/)([0-9A-Za-z_-]{11})._) had zero matches

Same error here on Linux when using a YouTube url.

However, on non YouTube "mode" local files that its full directory does not have spaces works just fine. Luckily there's [this pull request](https://github.com/carykh/jumpcutter/pull/87/commits/9d89f0ba0847287e4f83d45befcdb91f891fd50e) on the original jumpcutter that fixes this trouble with spaces.

Not feeling creating another issue for this since it's quite... _known?_ :laughing:

**Comment by soopyc** [comment]
lol just experienced this thing and a simple reinstall of pytube fixes the problem lol :)
