### ISSUE TITLE
Terribly slow.. 2.7x at best?

### ISSUE THREAD

**Issue by dewzor** [ThatOneCalculator/PyJumpcutterV2#2]
Thanks for this great app, awesome with a gui.

Im running it on a server with 32 threads E5-2670, SSD and 128gb ram, windows server 2012 R2. Works fine but its SUPER SLOW. At best 2.7x speed, i even created a ramdisk for it to work on but its not many frames faster with it. Any idea how i can speed it up?

**Comment by soopyc** [comment]
hi bro, if you're rendering on CPU, it will be a lot less faster than rendering on GPU. If you have a decent GPU, consider looking at [this](https://trac.ffmpeg.org/wiki/HWAccelIntro) article. Hope this helps:)
