### ISSUE TITLE
Just a thought to remove the need to install requirements.

### ISSUE THREAD

**Issue by jojomoore2007** [ThatOneCalculator/PyJumpcutterV2#5]
You might want to make an opener .sh and .cmd with the install commands for all of the requirements. Makes everything just a bit easier to use for tech n00bs.

>`master/`
>>`run.cmd`
>>```
>>pip install Pillow audiotsm scipy numpy pytube
>>python3 main.py
>>```
>
>>`run.sh`
>>```
>>pip install Pillow audiotsm scipy numpy pytube
>>python3 main.py
>>```

(P.S.: The two seperate files aren't different. The only reason for having two is because Windows will run .cmd files when double-clicked, and Linux will do the same for .sh files, but neither will open the other's.)

**Comment by ThatOneCalculator** [comment]
This doesnt really work cross-platform, `pip install -r requirements.txt` is fine
