### ISSUE TITLE
[Bug] Entering a custom value for frame_margin isn't in the GUI when using custom options.

### ISSUE THREAD

**Issue by pullup** [ThatOneCalculator/PyJumpcutterV2#8]
As the title says, I think  you must've accidentally left out the frame_margin setting which tends to be quite important sometimes. 

Love your project and I appreciate you making it <3

**Comment by scarpa27** [comment]
He didn't. It asks for silence threshold twice, first one is actually silence threshold, second time it is frame spreadage (he made a small mistake)
