### ISSUE TITLE
problem with temp file

### ISSUE THREAD

**Issue by jossebul** [ThatOneCalculator/PyJumpcutterV2#9]
Traceback (most recent call last):
  File "C:\Users\BULOT Josselin\AppData\Local\Programs\Python\Python37\PyJumpcutterV2-master\jumpcutter.py", line 35, in createPath
    os.mkdir(s)
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'TEMP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BULOT Josselin\AppData\Local\Programs\Python\Python37\PyJumpcutterV2-master\jumpcutter.py", line 123, in <module>
    createPath(TEMP_FOLDER)
  File "C:\Users\BULOT Josselin\AppData\Local\Programs\Python\Python37\PyJumpcutterV2-master\jumpcutter.py", line 37, in createPath
    assert False, "Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)"
AssertionError: Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)

and when I go to temp file

ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
TEMP/input.mp4: No such file or directory

**Comment by ThatOneCalculator** [comment]
Remove the TEMP folder
